<?php $produits=[ 
    (new Produit())
    ->setIndex(0)
    ->setNom('bonnet en laine')
    ->setprix(5)
    ->setDesc("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a leo diam. Quisque lorem orci, accumsan quis dolor sed, gravida.")
    ->setImg("https://picsum.photos/200")
    ->addMaterial("cachemire")
        ->addSize('S')
        ->addSize('M')
        ->addSize('L')
        ->addSize('XL')

    ,
    (new Produit())
    ->setIndex(1)
    ->setNom('bonnet en laine bio')
    ->setprix(30)
    ->setDesc("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a leo diam. Quisque lorem orci, accumsan quis dolor sed, gravida.")
    ->setImg("https://picsum.photos/200")
    ->addMaterial("laine")
        ->addSize('S')
        ->addSize('M')
        ->addSize('L')
        ->addSize('XL')
    ,
    (new Produit())
    ->setIndex(2)
    ->setNom('bonnet en laine et cachemir')
    ->setprix(20)
    ->setDesc("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a leo diam. Quisque lorem orci, accumsan quis dolor sed, gravida.")
    ->setImg("https://picsum.photos/200")
    ->addMaterial("soie")
        ->addSize('S')
        ->addSize('M')
        ->addSize('L')
        ->addSize('XL')
    ,
    (new Produit())
    ->setIndex(3)
    ->setNom('bonnet arc en ciel')
    ->setprix(15)
    ->setDesc("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a leo diam. Quisque lorem orci, accumsan quis dolor sed, gravida.")
    ->setImg("https://picsum.photos/200")
    ->addMaterial("coton")
        ->addSize('S')
        ->addSize('M')
        ->addSize('L')
        ->addSize('XL')
    ,
        ];

$mdp='azaz';